#+STARTUP: showall
* ut.umu

Log: [[https://umus.github.io/log/last-session][Most Recent Session]]
* Courses

** MAT157

Contact: [[https://www.math.toronto.edu/cms/repka-joe/][Professor Joe Repka]]

** MAT240

Contact: [[http://www.math.toronto.edu/mein/][Professor Eckhard Meinrenken]]

Course Homepage: [[http://www.math.toronto.edu/mein/teaching/MAT240/MAT240.html][2016 Fall MAT240]]

* Suggestions

/The following are the suggestions and opinions from the participants/
/regarding the sessions. The text is reproduced exactly as it has been/
/received/.

- Don't interrupt when ppl talking , be polite, don't spend too much
  time on one single question. Don't judge, don't copy but actually
  know how to do the question. Be productive. Don't be too serious but
  don't be too casual.

-  Work through extra Spivak chapters, work through baby Rudin if we
  are confident in our MAT157 material. I would also like to work on
  MAT240 if everyone is okay with that because I'm less confident in
  that material.

- Rule: Be prepared! Everybody should be familiar with the
  material we are discussing. AND do not idle for more than 3
  minutes. It’s time-killing and may distract other people.

- Topics Interested:
  + Course Materials, these things are fundamental.
  + Further discussion based on Complex Numbers, e.g. Laurent expansion
  + Number Theory, Probability, and much more.

- I'm mostly interested reviewing the week's lectures and working on
  relevant problems to cement our understanding of the material. Like
  some of us mentioned tonight, I think questions from Spivak,
  Prof. Meinrenken's bonus questions, and problem sets/tests from
  previous years are good places to start. I'm open to looking at
  other topics if other people are interested, but my primary concern
  is mastery of the material at hand.

- I think it might be useful to identify our topics of discussion a
  few days ahead of time so everyone has sufficient time to prepare
  and come up with questions, discover areas of confusion, etc.

- We could also consider inviting one of the profs to a part of our
  session sometime, since we're such a large group. They'd probably
  appreciate the enthusiasm.
